//get
export const GET_COURSES_REQUEST = "GET_COURSES_REQUEST";
export const GET_COURSES_SUCCESS = "GET_COURSES_SUCCESS";
export const GET_COURSES_FAILURE = "GET_COURSES_FAILURE";
//get course datails
export const GET_COURSE_REQUEST = "GET_COURSE_REQUEST";
export const GET_COURSE_SUCCESS = "GET_COURSE_SUCCESS";
export const GET_COURSE_FAILURE = "GET_COURSE_FAILURE";
//get enrollment
export const GET_ENROLLMENTS_REQUEST = "GET_ENROLLMENTS_REQUEST";
export const GET_ENROLLMENTS_SUCCESS = "GET_ENROLLMENTS_SUCCESS";
export const GET_ENROLLMENTS_FAILURE = "GET_ENROLLMENTS_FAILURE";
//get my grades
export const GET_GRADES_REQUEST = "GET_GRADES_REQUEST";
export const GET_GRADES_SUCCESS = "GET_GRADES_SUCCESS";
export const GET_GRADES_FAILURE = "GET_GRADES_FAILURE";

//enrollment
export const ENROLL_COURSE_REQUEST = "ENROLL_COURSE_REQUEST";
export const ENROLL_COURSE_SUCCESS = "ENROLL_COURSE_SUCCESS";
export const ENROLL_COURSE_FAILURE = "ENROLL_COURSE_FAILURE";

//DDELET ENROLLMENT
export const CANCEL_ENROLLMENTS_REQUEST = "CANCEL_ENROLLMENTS_REQUEST";
export const CANCEL_ENROLLMENTS_SUCCESS = "CANCEL_ENROLLMENTS_SUCCESS";
export const CANCEL_ENROLLMENTS_FAILURE = "CANCEL_ENROLLMENTS_FAILURE";