//email recover password

export const SEND_RECOVERY_EMAIL_PASS_REQUEST = "SEND_RECOVERY_EMAIL_REQUEST";
export const SEND_RECOVERY_EMAIL_PASS_SUCCESS = "SEND_RECOVERY_EMAIL_SUCCESS";
export const SEND_RECOVERY_EMAIL_PASS_FAILURE = "SEND_RECOVERY_EMAIL_FAILURE";

//reset password
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS ";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";

export const CLEAR_ALL_MESSAGES = "CLEAR_ALL_MESSAGES";