//login - logout
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";

// register student
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

//email recover password

export const SEND_RECOVERY_EMAIL_PASS_REQUEST = "SEND_RECOVERY_EMAIL_REQUEST";
export const SEND_RECOVERY_EMAIL_PASS_SUCCESS = "SEND_RECOVERY_EMAIL_SUCCESS";
export const SEND_RECOVERY_EMAIL_PASS_FAILURE = "SEND_RECOVERY_EMAIL_FAILURE";

//reset password
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS ";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";

export const CLEAR_ALL_MESSAGES = "CLEAR_ALL_MESSAGES";

//get states -> solo admin

export const GET_STATES_GENERAL_REQUEST = "GET_STATES_GENERAL_REQUEST";
export const GET_STATES_GENERAL_SUCCESS = "GET_STATES_GENERAL_SUCCESS";
export const GET_STATES_GENERAL_FAILURE = "GET_STATES_GENERAL_FAILURE";

// servicios solo para el superadmin
export const GET_USERS_REQUEST = "GET_USERS_REQUEST";

