//cursos
//get
export const GET_COURSES_REQUEST = "GET_COURSES_REQUEST";
export const GET_COURSES_SUCCESS= "GET_COURSES_SUCCESS";
export const GET_COURSES_FAILURE = "GET_COURSES_FAILURE";
//delete
export const DELETE_COURSE_REQUEST = "DELETE_COURSE_REQUEST";
export const DELETE_COURSE_SUCCESS= "DELETE_COURSE_SUCCESS";
export const DELETE_COURSE_FAILURE = "DELETE_COURSE_FAILURE";

//update
export const UPDATE_COURSE_REQUEST = "UPDATE_COURSE_REQUEST";
export const UPDATE_COURSE_SUCCESS= "UPDATE_COURSE_SUCCESS";
export const UPDATE_COURSE_FAILURE = "UPDATE_COURSE_FAILURE";

//add
export const ADD_COURSE_REQUEST = "ADD_COURSE_REQUEST";
export const ADD_COURSE_SUCCESS= "ADD_COURSE_SUCCESS";
export const ADD_COURSE_FAILURE = "ADD_COURSE_FAILURE";

//inscripciones
export const GET_ENROLLMENTS_BY_COURSE_REQUEST = "GET_ENROLLMENTS_BY_COURSE_REQUEST";
export const GET_ENROLLMENTS_BY_COURSE_SUCCESS = "GET_ENROLLMENTS_BY_COURSE_SUCCESS";
export const GET_ENROLLMENTS_BY_COURSE_FAILURE = "GET_ENROLLMENTS_BY_COURSE_FAILURE";


//get
export const GET_GRADE_REQUEST = "GET_GRADE_REQUEST";
export const GET_GRADE_SUCCESS = "GET_GRADE_SUCCESS";
export const GET_GRADE_FAILURE = "GET_GRADE_FAILURE";
//grades
export const ADD_GRADE_REQUEST = "ADD_GRADE_REQUEST";
export const ADD_GRADE_SUCCESS = "ADD_GRADE_SUCCESS";
export const ADD_GRADE_FAILURE = "ADD_GRADE_FAILURE";
